### PR TITLE
[afl++] fix input file mmap error handling

### PR DESCRIPTION
**Pull request by korniltsev**
size_t is unsigned and never negative
fprintf was segfaulting

### CODE REVIEW

**Comment by domenukk** [comment]
Oh wow, yet another fail, thanks you! 
Is `off_t` even an okay type to use for `uc_afl_mmap_file` or should we switch to `loff_t`? Right now, mapping a file with exactly 4GiB on 32 bit systems would map correctly and the return would be interpreted as error (`-1`) - but that is super unlikely to happen, even impossible for AFL...

**Comment by korniltsev** [comment]
ok, let me update it to stat64 + off64_t

**Comment by korniltsev** [comment]
actually lets not change anything, stat will return EOVERFLOW on linux and it won't mmap.
I don't see any reason to fuzz with gygabyte-size seeds.

**Comment by domenukk** [comment]
I agree. Thanks for the PRs! :) Let me know if you run into further issues. Will write some tests and update afl++ tonight.

**Comment by korniltsev** [comment]
there was one more minor issue with context dumper for pwndbg 
https://github.com/korniltsev/AFLplusplus/commit/18da206b1802e9935c85704f2c42b18fd1f1b10c#diff-6999e1111de14b193a527d4a8ef6a0e5R168
but I have no time right now to debug & PR it.

**Pull request merged**
