### PR TITLE
[afl++] fix segfault (using input buf after unmap)

### PR DESCRIPTION
**Pull request by korniltsev**

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Ty!

**Comment by domenukk** [comment]
Ah wow thanks for tracking this down! We/I should probably add a testcase that makes use of `validate_crash_callback` as this is a regression introduced in Commit ec637ff7ecb8328295fd77fe89d75443c9971c3a

**Comment by domenukk** [comment]
I'll change the repo ref in afl++ later to use the patched version.

**Comment by korniltsev** [comment]
@domenukk could you please take a look at https://github.com/vanhauser-thc/unicorn/pull/4 before updating refs?

**Pull request merged**
